;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        js3-mode-show-node
        subword-left
        subword-right
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        mouse-buffer-menu
        ))
