;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        haml-electric-backspace
        hippie-expand-no-case-fold
        js2-end-of-line
        js3-mode-show-node
        kill-region-or-backward-word
        subword-left
        subword-right
        tagedit-insert-equal
        tagedit-insert-lt
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ibuffer
        js2-mode-show-node
        mouse-buffer-menu
        mouse-drag-vertical-line
        mouse-set-region
        ))
